# Generated by Django 6.0.1 on 2026-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Місто/Регіон')),
                ('areas_of_help', models.JSONField(verbose_name='Напрямок допомоги')),
                ('motivation', models.TextField(verbose_name='Мотивація')),
                ('availability', models.CharField(max_length=50, verbose_name='Доступність')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Додаткова інформація')),
                ('consent_data_processing', models.BooleanField(verbose_name='Згода з обробкою даних')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
