# Generated by Django 6.0.1 on 2026-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('rescue_date', models.DateField(blank=True, default=None, verbose_name='Rescue Date')),
                ('history', models.TextField(blank=True, default=None, verbose_name='Personal History')),
                ('medical_data', models.TextField(blank=True, default=None, null=True, verbose_name='Medical Data')),
                ('status', models.CharField(choices=[('treatment', 'On a treatment'), ('rehabilitation', 'On a rehabilitation'), ('released', 'Released'), ('permanent', 'Permanent resident')], default='treatment', max_length=20, verbose_name='Treatment Status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Profile creation date')),
            ],
            options={
                'verbose_name': 'Seal',
                'verbose_name_plural': 'Seals',
            },
        ),
        migrations.CreateModel(
            name='SealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seals/gallery/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main image')),
            ],
            options={
                'verbose_name': 'Seal image',
                'verbose_name_plural': 'Seal images',
            },
        ),
        migrations.CreateModel(
            name='SealUpdateFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Update title')),
                ('content', models.TextField(verbose_name='Update text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates Feed',
                'ordering': ['-created_at'],
            },
        ),
    ]
