# Generated by Django 6.0.1 on 2026-02-22 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='adopted_seals', to=settings.AUTH_USER_MODEL, verbose_name='Volunteers'),
        ),
        migrations.AddField(
            model_name='sealimage',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seals.seal'),
        ),
        migrations.AddField(
            model_name='sealupdatefeed',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='seals.seal'),
        ),
    ]
