# Generated by Django 6.0.1 on 2026-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Funding Goal'),
        ),
    ]
