# Generated by Django 6.0.1 on 2026-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Certificate Name')),
                ('file', models.FileField(upload_to='profiles/certificates/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('bio', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('social_shares_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('amoled', 'Amoled')], default='light', max_length=20)),
                ('font_style', models.CharField(choices=[('standard', 'Standard'), ('serif', 'Serif'), ('mono', 'Monospaced')], default='standard', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
